;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        crux-smart-open-line-above
        delete-horizontal-space
        easy-kill
        electric-newline-and-maybe-indent
        eval-print-last-sexp
        indent-for-tab-command
        kill-region
        kill-sexp
        org-delete-char
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-sexp
        sp-delete-char
        sp-forward-barf-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-splice-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
